name: CI

on:
  push:
    branches:
    - main
  pull_request:

env:
  # The NAME makes it easier to copy/paste snippets from other CI configs
  NAME: sql-cli

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.10.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3

    - name: Deps
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Lint
      run: |
        black --check sql_cli
        mypy sql_cli

    - name: Build
      run: |
        ./setup.py build
